// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGBrbJSnmPL_hsT0fG3rm_phxYm8ez58',
    appId: '1:273050868173:web:e314f0ea22e5d399574c84',
    messagingSenderId: '273050868173',
    projectId: 'ai-bot-16831',
    authDomain: 'ai-bot-16831.firebaseapp.com',
    storageBucket: 'ai-bot-16831.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LJCy0xe9CJt3ssE74VztOJukpaBerso',
    appId: '1:273050868173:android:ef13515d6c14f2cc574c84',
    messagingSenderId: '273050868173',
    projectId: 'ai-bot-16831',
    storageBucket: 'ai-bot-16831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hIW_nCqZmdadlzs2fzIZpeyP1itIGUY',
    appId: '1:273050868173:ios:ebb6d35ac0365d74574c84',
    messagingSenderId: '273050868173',
    projectId: 'ai-bot-16831',
    storageBucket: 'ai-bot-16831.appspot.com',
    iosClientId: '273050868173-2oh2vedd0dob3sk8akmn4ieugj8lq3qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGptBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1hIW_nCqZmdadlzs2fzIZpeyP1itIGUY',
    appId: '1:273050868173:ios:5dd23effb1997192574c84',
    messagingSenderId: '273050868173',
    projectId: 'ai-bot-16831',
    storageBucket: 'ai-bot-16831.appspot.com',
    iosClientId: '273050868173-2u79apmeg0mlut9daefosm031g0j6m6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGptBot.RunnerTests',
  );
}
